export const houses = [
  {
    id: 1,
    label: "Luxury Apartment in Sandton",
    type: "house",
    thumbnailID: "0001",
    priceCents: 185000,
    rating: 4.8,
    location: "Johannesburg",
    description: "Modern apartment in the heart of Sandton with skyline views.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 2,
    offers: ["Wifi", "Pool", "Air Conditioning", "Free parking"],
    listingDate: "2025-03-01",
    hostDetails: { hostName: "Thabo", hostingPeriod: "2 years" }
  },
  {
    id: 2,
    label: "Beachfront Villa in Durban",
    type: "house",
    thumbnailID: "0002",
    priceCents: 320000,
    rating: 4.9,
    location: "Durban",
    description: "Wake up to ocean views in this spacious beachfront villa.",
    bedrooms: 3,
    guests: 6,
    bathrooms: 2,
    offers: ["Wifi", "Pool", "Ocean view", "Parking"],
    listingDate: "2025-03-02",
    hostDetails: { hostName: "Aisha", hostingPeriod: "3 years" }
  },
  {
    id: 3,
    label: "Cozy Studio in Cape Town",
    type: "house",
    thumbnailID: "0003",
    priceCents: 95000,
    rating: 4.4,
    location: "Cape Town",
    description: "Perfect for solo travelers, close to Table Mountain.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Workspace", "Mountain view"],
    listingDate: "2025-03-03",
    hostDetails: { hostName: "Lerato", hostingPeriod: "1 year" }
  },
  {
    id: 4,
    label: "Modern Loft in Pretoria",
    type: "house",
    thumbnailID: "0004",
    priceCents: 120000,
    rating: 4.6,
    location: "Pretoria",
    description: "Stylish loft with open-plan design and city views.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Air Conditioning", "Parking"],
    listingDate: "2025-03-04",
    hostDetails: { hostName: "Daniel", hostingPeriod: "5 years" }
  },
  {
    id: 5,
    label: "Safari Lodge in Kruger",
    type: "house",
    thumbnailID: "0005",
    priceCents: 450000,
    rating: 5.0,
    location: "Kruger National Park",
    description: "Experience wildlife up close in this luxury safari lodge.",
    bedrooms: 4,
    guests: 8,
    bathrooms: 3,
    offers: ["Pool", "Guided tours", "All meals included"],
    listingDate: "2025-03-05",
    hostDetails: { hostName: "Sipho", hostingPeriod: "4 years" }
  },
  {
    id: 6,
    label: "Guesthouse in Stellenbosch",
    type: "house",
    thumbnailID: "0006",
    priceCents: 140000,
    rating: 4.7,
    location: "Stellenbosch",
    description: "Charming guesthouse surrounded by vineyards.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 2,
    offers: ["Wifi", "Breakfast", "Wine tours"],
    listingDate: "2025-03-06",
    hostDetails: { hostName: "Zanele", hostingPeriod: "2 years" }
  },
  {
    id: 7,
    label: "City Apartment in Johannesburg CBD",
    type: "house",
    thumbnailID: "0007",
    priceCents: 80000,
    rating: 4.1,
    location: "Johannesburg",
    description: "Affordable stay in the city center with easy transport access.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Security", "Parking"],
    listingDate: "2025-03-07",
    hostDetails: { hostName: "Kabelo", hostingPeriod: "1 year" }
  },
  {
    id: 8,
    label: "Luxury Penthouse in Cape Town",
    type: "house",
    thumbnailID: "0008",
    priceCents: 600000,
    rating: 4.9,
    location: "Cape Town",
    description: "Top-floor penthouse with panoramic ocean and city views.",
    bedrooms: 3,
    guests: 6,
    bathrooms: 3,
    offers: ["Wifi", "Pool", "Ocean view", "Balcony"],
    listingDate: "2025-03-08",
    hostDetails: { hostName: "Nina", hostingPeriod: "3 years" }
  },
  {
    id: 9,
    label: "Family Home in Bloemfontein",
    type: "house",
    thumbnailID: "0009",
    priceCents: 110000,
    rating: 4.3,
    location: "Bloemfontein",
    description: "Spacious home perfect for families and long stays.",
    bedrooms: 3,
    guests: 5,
    bathrooms: 2,
    offers: ["Wifi", "Parking", "Garden"],
    listingDate: "2025-03-09",
    hostDetails: { hostName: "Marcus", hostingPeriod: "2 years" }
  },
  {
    id: 10,
    label: "Mountain Cabin in Drakensberg",
    type: "house",
    thumbnailID: "0010",
    priceCents: 170000,
    rating: 4.8,
    location: "Drakensberg",
    description: "Peaceful cabin surrounded by mountains and nature.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 1,
    offers: ["Fireplace", "Hiking trails", "Mountain view"],
    listingDate: "2025-03-10",
    hostDetails: { hostName: "Ayanda", hostingPeriod: "4 years" }
  },
  {
    id: 11,
    label: "Seaside Cottage in Hermanus",
    type: "house",
    thumbnailID: "0011",
    priceCents: 210000,
    rating: 4.7,
    location: "Hermanus",
    description: "Cozy cottage perfect for whale watching season.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 1,
    offers: ["Ocean view", "Wifi", "Parking"],
    listingDate: "2025-03-11",
    hostDetails: { hostName: "Lebo", hostingPeriod: "2 years" }
  },
  {
    id: 12,
    label: "Budget Room in Soweto",
    type: "house",
    thumbnailID: "0012",
    priceCents: 45000,
    rating: 4.0,
    location: "Johannesburg",
    description: "Simple and affordable stay in a vibrant neighborhood.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi"],
    listingDate: "2025-03-12",
    hostDetails: { hostName: "Neo", hostingPeriod: "6 months" }
  },
  {
    id: 13,
    label: "Luxury Villa in Camps Bay",
    type: "house",
    thumbnailID: "0013",
    priceCents: 750000,
    rating: 5.0,
    location: "Cape Town",
    description: "Exclusive villa with infinity pool and beach views.",
    bedrooms: 5,
    guests: 10,
    bathrooms: 4,
    offers: ["Pool", "Ocean view", "Wifi", "Private chef"],
    listingDate: "2025-03-13",
    hostDetails: { hostName: "Jason", hostingPeriod: "5 years" }
  },
  {
    id: 14,
    label: "Tiny Home in Knysna",
    type: "house",
    thumbnailID: "0014",
    priceCents: 90000,
    rating: 4.5,
    location: "Knysna",
    description: "Minimalist tiny home surrounded by forest.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Nature view"],
    listingDate: "2025-03-14",
    hostDetails: { hostName: "Chloe", hostingPeriod: "1 year" }
  },
  {
    id: 15,
    label: "Modern Flat in Port Elizabeth",
    type: "house",
    thumbnailID: "0015",
    priceCents: 100000,
    rating: 4.2,
    location: "Port Elizabeth",
    description: "Clean and modern flat near the beach.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Parking"],
    listingDate: "2025-03-15",
    hostDetails: { hostName: "Ethan", hostingPeriod: "2 years" }
  },
  {
    id: 16,
    label: "Farm Stay in Limpopo",
    type: "house",
    thumbnailID: "0016",
    priceCents: 130000,
    rating: 4.6,
    location: "Limpopo",
    description: "Relaxing farm stay with wide open landscapes.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 1,
    offers: ["Nature", "Parking"],
    listingDate: "2025-03-16",
    hostDetails: { hostName: "Nomsa", hostingPeriod: "3 years" }
  },
  {
    id: 17,
    label: "City Loft in Durban",
    type: "house",
    thumbnailID: "0017",
    priceCents: 115000,
    rating: 4.3,
    location: "Durban",
    description: "Modern loft close to nightlife and beaches.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Air Conditioning"],
    listingDate: "2025-03-17",
    hostDetails: { hostName: "Ryan", hostingPeriod: "1 year" }
  },
  {
    id: 18,
    label: "Eco Cabin in Mpumalanga",
    type: "house",
    thumbnailID: "0018",
    priceCents: 150000,
    rating: 4.7,
    location: "Mpumalanga",
    description: "Sustainable cabin with solar power and forest views.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 1,
    offers: ["Solar power", "Nature", "Hiking"],
    listingDate: "2025-03-18",
    hostDetails: { hostName: "Mia", hostingPeriod: "2 years" }
  },
  {
    id: 19,
    label: "Studio in Braamfontein",
    type: "house",
    thumbnailID: "0019",
    priceCents: 70000,
    rating: 4.1,
    location: "Johannesburg",
    description: "Compact studio ideal for students and young professionals.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi"],
    listingDate: "2025-03-19",
    hostDetails: { hostName: "Liam", hostingPeriod: "6 months" }
  },
  {
    id: 20,
    label: "Luxury Estate in Stellenbosch",
    type: "house",
    thumbnailID: "0020",
    priceCents: 680000,
    rating: 4.9,
    location: "Stellenbosch",
    description: "Elegant estate surrounded by vineyards.",
    bedrooms: 4,
    guests: 8,
    bathrooms: 3,
    offers: ["Pool", "Wine tasting", "Wifi"],
    listingDate: "2025-03-20",
    hostDetails: { hostName: "Sophia", hostingPeriod: "5 years" }
  },
  {
    id: 21,
    label: "Cliffside House in Tsitsikamma",
    type: "house",
    thumbnailID: "0021",
    priceCents: 240000,
    rating: 4.8,
    location: "Tsitsikamma",
    description: "Breathtaking views from this cliffside retreat.",
    bedrooms: 3,
    guests: 6,
    bathrooms: 2,
    offers: ["Ocean view", "Hiking"],
    listingDate: "2025-03-21",
    hostDetails: { hostName: "Noah", hostingPeriod: "3 years" }
  },
  {
    id: 22,
    label: "Urban Apartment in Midrand",
    type: "house",
    thumbnailID: "0022",
    priceCents: 95000,
    rating: 4.2,
    location: "Midrand",
    description: "Convenient apartment between Johannesburg and Pretoria.",
    bedrooms: 1,
    guests: 2,
    bathrooms: 1,
    offers: ["Wifi", "Parking"],
    listingDate: "2025-03-22",
    hostDetails: { hostName: "Olivia", hostingPeriod: "1 year" }
  },
  {
    id: 23,
    label: "Beach House in Ballito",
    type: "house",
    thumbnailID: "0023",
    priceCents: 300000,
    rating: 4.7,
    location: "Ballito",
    description: "Spacious beach house perfect for groups.",
    bedrooms: 4,
    guests: 8,
    bathrooms: 3,
    offers: ["Pool", "Ocean view", "Wifi"],
    listingDate: "2025-03-23",
    hostDetails: { hostName: "Ethan", hostingPeriod: "4 years" }
  },
  {
    id: 24,
    label: "Countryside Cottage in Clarens",
    type: "house",
    thumbnailID: "0024",
    priceCents: 160000,
    rating: 4.6,
    location: "Clarens",
    description: "Quiet cottage surrounded by mountains and art galleries.",
    bedrooms: 2,
    guests: 4,
    bathrooms: 1,
    offers: ["Fireplace", "Mountain view"],
    listingDate: "2025-03-24",
    hostDetails: { hostName: "Grace", hostingPeriod: "2 years" }
  },
  {
    id: 25,
    label: "Penthouse in Umhlanga",
    type: "house",
    thumbnailID: "0025",
    priceCents: 520000,
    rating: 4.9,
    location: "Umhlanga",
    description: "Luxury penthouse with stunning oceanfront views.",
    bedrooms: 3,
    guests: 6,
    bathrooms: 3,
    offers: ["Pool", "Ocean view", "Wifi", "Balcony"],
    listingDate: "2025-03-25",
    hostDetails: { hostName: "Michael", hostingPeriod: "5 years" }
  }
];